todo/urls.py
from django.contrib import admin
from django.urls import path, include

from todo.views import (
    TaskListView,
    TaskCreateView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskUpdateView,
    TaskDeleteView,
    TaskToggleStatusView
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path('tags/', TagListView.as_view(), name='tag-list'),
    path('tags/create/', TagCreateView.as_view(), name='tag-create'),
    path('tags/<int:pk>/update/', TagUpdateView.as_view(), name='tag-update'),
    path('tags/<int:pk>/delete/', TagDeleteView.as_view(), name='tag-delete'),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/toggle-status/", TaskToggleStatusView.as_view(), name="task-toggle-status"),
]

todo_config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("todo.urls", "todo"), namespace="todo")),
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField()
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-datetime"]

todo/forms.py
from django import forms

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = ("__all__")


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ("__all__")

todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm, TagForm
from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 3


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


class TaskToggleStatusView(generic.View):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.is_done = not task.is_done
        task.save()
        return redirect("todo:task-list")


class TagListView(generic.ListView):
    model = Tag
    template_name = 'todo_list/tag_list.html'
    context_object_name = 'tags'
    paginate_by = 10


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('todo:tag-list')


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('todo:tag-list')


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy('todo:tag-list')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Todo list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">Prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">Next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}"><strong>Tasks</strong></a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}"><strong>Tags</strong></a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete "{{ object.name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="{% url 'todo:tag-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy}}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>Tag list</h1>
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary">Create</a>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Tag Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for tag in tags %}
        <tr>
          <td>{{ tag.name }}</td>
          <td>
            <a href="{% url 'todo:tag-update' tag.pk %}" class="btn btn-secondary">Update</a>
          </td>
          <td>
            <a href="{% url 'todo:tag-delete' tag.pk %}" class="btn btn-secondary">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Confirm Deletion</h1>
  <p>Are you sure you want to delete this task?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-danger">
    <a href="{% url 'todo:task-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy}}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>TODO list</h1>
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary">Create</a>
  </div>
  {% for task in task_list %}
    <div class="d-flex justify-content-between align-items-center border-bottom border-secondary mb-3">
      <ul class="list">
        <li>
          <strong>
            {{ task.content }}
            {% if task.is_done %}
              <span class="text-success">
                Done
              </span>
            {% else %}
              <span class="text-danger">
                Not done
              </span>
            {% endif %}
          </strong>
        </li>
        <li>
          <p>Created at {{ task.datetime }} {% if task.deadline %}<span class="danger">Deadline: {{ task.deadline }}</span>{% endif %}</p>
        </li>
        <li>
          <div class="d-flex flex-row">
            {% if task.tags.all %}
              {% for tag in task.tags.all %}
                <p class="text-secondary pr-1">{{ tag.name }}</p>
              {% endfor %}
            {% else %}
              <p>There are no tags</p>
            {% endif %}
            <a href="{% url 'todo:task-update' pk=task.id %}" class="text-primary pr-1">Update</a>
            <a href="{% url 'todo:task-delete' pk=task.id %}" class="text-primary pr-1">Delete</a>
          </div>
        </li>
      </ul>
      {% if task.is_done %}
        <a href="{% url 'todo:task-toggle-status' pk=task.pk %}" class="btn btn-secondary ml-auto">
          Undo
        </a>
      {% else %}
        <a href="{% url 'todo:task-toggle-status' pk=task.pk %}" class="btn btn-success ml-auto align-middle">
          Complete
        </a>
      {% endif %}
    </div>
  {% endfor %}
{% endblock %}